### ISSUE TITLE
Any ideas for testing?

### ISSUE THREAD

**Issue by Jeiwan** [joshuamiller/map-todo-demo#1]
Hi!

Thanks for sharing this demo project, it's really helpful!
In our project we also want to build a RN app with ClojureScript, but finding a good testing solution is a big problem for us. Ideally, we want to use Jest to mock RN components, but it seems that the JS code produced by the CLJS compiler doesn't work in Jest. We tried different CLJS compiler `optimization` options and got stuck on different issues.

Could you please share your testing solution?

**Comment by joshuamiller** [comment]
Hi @Jeiwan, glad you like it. Unfortunately I don't have a good end-to-end testing solution yet; I've just been testing my ClojureScript on its own. The best place to ask would probably be the `#cljsrn` channel on http://clojurians.slack.com/

**Comment by Jeiwan** [comment]
Got it, thanks!
